//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileOpsPilotData.Repository.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriftdownDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid FlightPlanId { get; set; }
        public string Text { get; set; }
        public string Altitude { get; set; }
        public string MelPenalty { get; set; }
        public string IsaDeviation { get; set; }
        public string TerrainClearanceDeltaWeight { get; set; }
        public string RampWeight { get; set; }
        public string TerrainClearanceWeight { get; set; }
        public string PayloadPad { get; set; }
        public string IataPoa { get; set; }
        public string IcaoPoa { get; set; }
        public string IataPod { get; set; }
        public string IcaoPod { get; set; }
        public string AntiIce { get; set; }
        public string TextVersion2Header { get; set; }
        public string TextVersion2 { get; set; }
        public string VersionHash { get; set; }
    
        public virtual FlightPlan FlightPlan { get; set; }
    }
}
