//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileOpsPilotData.Repository.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightPlan()
        {
            this.DriftdownDetails = new HashSet<DriftdownDetail>();
            this.FlightDetails = new HashSet<FlightDetail>();
            this.WindReports = new HashSet<WindReport>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid FlightId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string FlightNumber { get; set; }
        public string IataAirlineCode { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string Dispatcher { get; set; }
        public string DispatchDesk { get; set; }
        public string DispatchPhone { get; set; }
        public string Remarks { get; set; }
        public string VersionHash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriftdownDetail> DriftdownDetails { get; set; }
        public virtual Flight Flight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightDetail> FlightDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WindReport> WindReports { get; set; }
    }
}
