//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileOpsPilotData.Repository.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class WindFlighLevelDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid WindCheckpointId { get; set; }
        public string Temperature { get; set; }
        public string WindVelocity { get; set; }
        public string WindDirection { get; set; }
        public string WindShear { get; set; }
        public string Level { get; set; }
        public string VersionHash { get; set; }
    
        public virtual WindCheckpoint WindCheckpoint { get; set; }
    }
}
