//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileOpsPilotData.Repository.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class WindReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WindReport()
        {
            this.WindCheckpoints = new HashSet<WindCheckpoint>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid FlightPlanId { get; set; }
        public string VersionHash { get; set; }
    
        public virtual FlightPlan FlightPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WindCheckpoint> WindCheckpoints { get; set; }
    }
}
