//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileOpsPilotData.Repository.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class WindCheckpoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WindCheckpoint()
        {
            this.WindFlighLevelDetails = new HashSet<WindFlighLevelDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid WindReportId { get; set; }
        public string CheckpointName { get; set; }
        public string VersionHash { get; set; }
    
        public virtual WindReport WindReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WindFlighLevelDetail> WindFlighLevelDetails { get; set; }
    }
}
